--- Dockerfile.orig	2025-04-14 19:33:21.061246340 +0000
+++ Dockerfile	2025-05-03 03:01:03.493095744 +0000
@@ -10,7 +10,7 @@
 libcap-ng-dev pkg-config libvncserver-dev software-properties-common \
 git libjpeg-dev libsasl2-dev libncurses5-dev libncursesw5-dev \
 libgtk-3-dev libsdl2-dev screen parallel \
-htop cpulimit meson autoconf-archive libopus-dev zip unzip sudo
+htop cpulimit meson autoconf-archive libopus-dev zip unzip sudo linux-headers-$(uname -r)
 
 RUN apt-get install -y curl
 RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
@@ -65,12 +65,13 @@
 # fix missing slirp
 RUN apt-get install -y libslirp-dev
 
+RUN apt-get install -y gcc-12 g++-12
+
+RUN apt-get install -y tmux rustc
+
 FROM base as development
 
 # update llvm toolchains
 RUN python3 -m pip install --upgrade --no-cache-dir gdown \
     --disable-pip-version-check --root-user-action=ignore
-RUN mkdir llvm-project
-RUN cd llvm-project && gdown https://drive.google.com/uc?id=1bHHYPwpmFaEvhkNcZuCa_Fbk8A41IEJr && \
-tar xf llvm-project-13.tar.gz && cd $OLDPWD
 ENV PATH=/root/llvm-project/bin:$PATH
